version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
      time: "10:00"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"