apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "simple-pushgateway.fullname" . }}
  labels:
    {{- include "simple-pushgateway.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{ end }}
  selector:
    matchLabels:
      {{- include "simple-pushgateway.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "simple-pushgateway.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: "pushgateway"
        image: {{ .Values.containers.pushgateway.image.repository }}:{{ default .Chart.AppVersion .Values.containers.pushgateway.image.tag }}
        imagePullPolicy: {{ .Values.containers.pushgateway.image.pullPolicy | quote }}
        {{- with .Values.containers.pushgateway.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.containers.pushgateway.serverPort }}
            protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.containers.pushgateway.args }}
        args: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.containers.pushgateway.env }}
        env:
        {{- range $key, $value := . }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
