kind: Service
apiVersion: v1
metadata:
  name: {{ template "simple-pushgateway.fullname" . }}
  labels:
    {{- include "simple-pushgateway.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  selector:
    {{- include "simple-pushgateway.selectorLabels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http